### ISSUE TITLE
Не отцентровано расписание звонков!!!!!!!!!!

### ISSUE THREAD

**Issue by Rasakhatskiy** [Andreychik32/angular-bibip#1]
**Не отцентровано расписание звонков!!!!!!!!!!** 😡😡😡😡😡😡

**Comment by pogrib0k** [comment]
Автор ты сука! Так и должно быть. Твоя мать он тоже не отцентрована, ей ты так же не говоришь.

**Comment by Rasakhatskiy** [comment]
Категорически несогласен с точкой зрения автора выше. Я считаю что бесборадок в расписании приводит к беспорядку в голове и из-за этого студенты Национального Университета Биоресурсов и Природоиспользования Украины не смогут нормально получать так необходимую им в наши дни информацию.
![icon-192x192](https://user-images.githubusercontent.com/25859865/76768532-ce7f4980-67a3-11ea-97c0-68010b8c25f3.png)
Слава отцентрованным расписаниям!

**Comment by pogrib0k** [comment]
Я извеняюсь, но откуда Вам знать какого студентам Национального Университета Биоресурсов и Природоиспользования Украины, я являясь студентом этого прекрасного университета не испытываю никаких трудностей. Скорее всего Вы учитесь в другом университете.

**Comment by Rasakhatskiy** [comment]
Лох

**Comment by Andreychik32** [comment]
@Rasakhatskiy, могу сказать, что если бы студенты Национального Университета Биоресурсов и Природопользования Украины хотели что-то изменить в данном приложении, чтобы получать так необходимую им в наши дни информацию, они бы совершенно бесплатно, с регистрацией и без смс зашли бы [сюда](https://github.com/Andreychik32/angular-bibip/pulls) и оформили свои претензии в виде изменений в код, которые эти же студенты хотели бы видеть в приложении.

Распространите это среди жителей своего ЖЕКа, как вы это любите.

**Comment by Rasakhatskiy** [comment]
@pogrib0k 
Ну давай удаляй дальше, сразу видко каких студентов учать в сельхоз академии.
@Andreychik32 
Заходить в ваши пульреквесты я не собираюсь у меня естб свой таймтебл.

**Comment by Andreychik32** [comment]
Отцентровали.

**Comment by Rasakhatskiy** [comment]
Спасибо огромное, студенты Национального Университета Биоресурсов и Природопользования Украины будут вам благодарны.
